name: Run Python Simulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Set the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install statistics  # Ensure dependencies are installed (standard library for your script)

    - name: Run simulation
      run: python main.py

    - name: Upload simulation results
      if: success()
      run: echo "Simulation completed successfully!"
